language: groovy
jdk:
- oraclejdk7
sudo: false
before_install:
- export TZ=Europe/Stockholm
- date
- rm -rf ~/.sdkman
- curl -s http://get.sdkman.io | bash
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- GRAILS_VERSION=`grep '^app\.grails\.version=' ./application.properties | sed -e
  's/^app\.grails\.version=//g'`
- sdk install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g' | tr -d "\r"`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy"; fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails
- wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive
deploy:
  provider: releases
  api_key:
    secure: leiaGfMPDmjlLTdriv3TGCZofv6ehMPbj0TBL5eqlp66rhmZHSBKsw5wOrFIC1hReKo9De45v9EaQDNqOphi35cyFbLD86geynmret4gxmkM2OAMdBnT9N2i/VcX46Ve+SQ4CHbdhBHwiFYd/pfZHwZPn9mguxhHHiMS5dA19P++LsuZ12Qq5OnXCGAY7g9tqnzM1KP3YK0dYVdUrzk3rGBAxTnmxho7WnpsLg/4ZgaW7I2uevkbCk+MxSA8n4eetAUybutp8tMQWx1tL78m1N8QkU5xzO8LOgVAeN2/7CmxxBreq6Laq5PCEXEHpIyO+obmOomDEK5D7sIchgmMD5Fhq5+CiJhb3DZ5xF0BjV2j5Wy3SYSviyiGVN35cgImA/AUAG4MU4O9JEfs6cB6nE0ROxOFjOF4zqRIL+EFxKEb5vfCMhv0H8mJBlZUbAo2N5U37DpyS13uruwTgh0ib9GUeNzL+Lwg8IQoTJ5HE2MTinInWoXRk4d/gkETRPGo0as7DMDJv9/Wa+n1bP9k+AL3Es7lzlnTWj0J8wOKpiWK/AxvVmIiY3sQ8OiAr8iRYM+L1XdovRvoGMSY+e3v8ODnAvDC/sAlo/yHXApRvEaltGVkc1AXQx8Etac/CZLJBlFKjzql3Gbw44fV96ihN43+Pd7jiFFAlRtPYcEGHeQ=
  file_glob: true
  file: "target/generic-collectory-*.war"
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/generic-collectory-sweden
    all-branches: true
    tags: true
